// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(ReportContext))]
    partial class ReportContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Infrastructure.Entities.Observation", b =>
                {
                    b.Property<int>("ObservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnimalID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExporterId")
                        .HasColumnType("int");

                    b.Property<string>("ExporterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HuntingFieldID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsCultivateLand")
                        .HasColumnType("bit");

                    b.Property<int>("NoCalf")
                        .HasColumnType("int");

                    b.Property<int>("NoElder")
                        .HasColumnType("int");

                    b.Property<int>("NoFemale")
                        .HasColumnType("int");

                    b.Property<int>("NoFemale1Calf")
                        .HasColumnType("int");

                    b.Property<int>("NoFemale2Calf")
                        .HasColumnType("int");

                    b.Property<int>("NoHours")
                        .HasColumnType("int");

                    b.Property<int>("NoHunters")
                        .HasColumnType("int");

                    b.Property<int>("NoMale")
                        .HasColumnType("int");

                    b.Property<int>("NoUnknown")
                        .HasColumnType("int");

                    b.HasKey("ObservationID");

                    b.ToTable("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
